trade:
  zhifu:
    qrcode:
      aliPayPath: /alipay
      weChatPath: /wechat
      storePath: D:/temp/qr-code
      httpBasePath: /static/qrcode
      paySuccessCallBack: http://wjdcrw.natapp1.cc/order/paySuccess